// Define your own mock data here:
export const standard = (/* vars, { ctx, req } */) => ({
  participant: {
    __typename: 'Participant' as const,
    id: '42',
    name: 'Max',
    familyName: 'Mustermann',
    birthdate: '2008-05-17',
    gender: 'male',
    phoneNumber: '+43 660 1234567',
    country: 'AT',
    city: 'Kremsmünster',
    postalCode: '4550',
    address: 'Stiftsplatz 1',
    travelMethod: 'train',
    accommodation: 'jugendtreffen',
    startDate: '2026-07-01',
    endDate: '2026-07-05',
    foodChoice: 'vegetarian',
    acceptPhotos: true,
    acceptCoC: true,
    participationRole: 'teilnehmer',
    event: {
      __typename: 'Event' as const,
      id: 1,
      name: 'Jugendtreffen 2026',
      startDate: '2026-07-01',
      endDate: '2026-07-05',
    },
  },
})
